version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "9092:9092"

  api_checker:
    build: ./api_checker
    volumes:
      - ./config:/app/config
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO

  websocket_server:
    build: ./websocket_server
    ports:
      - "8765:8765"   # WebSocket
      - "8766:8766"   # HTTP API
    depends_on:
      - kafka
    environment:
      - LOG_LEVEL=INFO

  client:
    build: ./client
    ports:
      - "8081:80"
    depends_on:
      - websocket_server